### ISSUE TITLE
pbmview - qoi decoding issue

### ISSUE THREAD

**Issue by STPR** [skeeto/scratch#4]
Hello,
While searching some qoi files to test your viewer, I've found an issue talking about an edge case in some qoi decoders:
[https://github.com/phoboslab/qoi/issues/258](https://github.com/phoboslab/qoi/issues/258)

And, like a lot of others decoders, your decoder fail to decode one of the file correctly.
The background of the file edgecase.qoi must be fully opaque black:
[https://qoiformat.org/qoi_test_images.zip](https://qoiformat.org/qoi_test_images.zip)

**Comment by skeeto** [comment]
Thanks! This should be fixed by not skipping the table insertion on runs, 
though that makes runs slightly more expensive. Now that I'm aware of the 
edge case, I wish the specification had set the first color to all zeros 
like the table itself.
