### ISSUE TITLE
cmdline_from_argv8: wrong handling of trailing backslash

### ISSUE THREAD

**Issue by bipface** [skeeto/scratch#7]
Example 1:
```
> gcc -DDEMO -o demo.exe cmdline.c
> demo.exe "c:\program files\\"
cmd = demo.exe  "c:\program files\\"
argc = 2
argv[0] = demo.exe             (8) 64 65 6d 6f 2e 65 78 65
argv[1] = c:\program files\    (17) 63 3a 5c 70 72 6f 67 72 61 6d 20 66 69 6c 65 73 5c
recmd = demo.exe "c:\program files\"
```
Notice the `recmd =` line not having the last slash escaped, even though it appears before a closing quote.
If we execute that command as it appears above:
```
> demo.exe "c:\program files\"
cmd = demo.exe  "c:\program files\"
argc = 2
argv[0] = demo.exe             (8) 64 65 6d 6f 2e 65 78 65
argv[1] = c:\program files"    (17) 63 3a 5c 70 72 6f 67 72 61 6d 20 66 69 6c 65 73 22
recmd = demo.exe "c:\program files\""
```
We get a different result, because the arg is interpreted as having unclosed quotes with an escaped quote at the end.

Expected output for example 1 would have been:
```
> demo.exe "c:\program files\\"
...
recmd = demo.exe "c:\program files\\"
```

**Comment by skeeto** [comment]
Thanks! Should be fixed now, along with your example as a new test. The 
problem was finishing while in a backslash-sequence state but not 
resolving that state before closing out a quoted argument.
